AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/StringLiterals:
  Description: "Use double quotes for strings."
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  Description: "Use double quotes for string interpolation."
  Enabled: true
  EnforcedStyle: double_quotes
